#failed tests will be rerun 2 times and the report will be generated in the reports folder with the name report.html

[pytest]

addopts = -v --reruns 2 --html=reports/report.html
testpaths = tests
pythonpath = .